import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import firebase from 'firebase/compat/app';
import { getAuth } from 'firebase/auth';

const Home: NextPage = () => {
  console.log('The firebase app:', firebase);
  console.log('The firebase app:', getAuth());
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        THis will be the intro to Next.js with React Query
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
